# ---------------
# Trainer hparams
# --------------- 
seed: 0
trainer:
  max_epochs: 5
  gpus: 1
  auto_select_gpus: True
  # fast_dev_run: True
# ---------------
# Model
# --------------- 
model:
  module: qan.models
  method: TransformersQA 
  args:
  # ---------------
  # Backbone
  # --------------- 
    model_cfg:
      encoder: 
        module: transformers
        method: BertModel
        args: 
          pretrained_model_name_or_path: bert-base-uncased
        config:
          module: transformers
          method: BertConfig
          args:
            hidden_size: 768
            num_hidden_layers: 4
            num_attention_heads: 12
            hidden_dropout_prob: 0.1
            attention_probs_dropout_prob: 0.1
            max_position_embeddings: 512
    optimizer_cfg:
      module: AdamW
      args:
        lr: 0.00005
        weight_decay: 0
    tokenizer_cfg: 
      module: transformers
      method: BertTokenizerFast
      args:
        pretrained_model_name_or_path: bert-base-uncased



# ---------------------------
# Datasets and Dataloader
# ---------------------------
dataloader:
  module: qan.datasets.squad
  method: SQUADDataLoader
  args:
    dataset: squad
    trainLoader_cfg:
      batch_size: 3 
      shuffle: True
      num_workers: 12
    valLoader_cfg:
      batch_size: 20
      shuffle: False
      num_workers: 4

# ---------------
# Logger
# --------------- 
logger:
  module: pytorch_lightning.loggers
  method: TensorBoardLogger
  args:
    save_dir: logs/
    name: bert_squadv1
    log_graph: True

